// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOvmdDfo0dPIwDKjL9rmeQ7mNx34AbvR0',
    appId: '1:919362131099:web:17dbeb536320a266dee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    authDomain: 'fir-series-2d91e.firebaseapp.com',
    databaseURL: 'https://fir-series-2d91e-default-rtdb.firebaseio.com',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    measurementId: 'G-Y9E1LP1N2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZhF5fPqSpK8cFi15ZiyHcgvusQyZ4yEY',
    appId: '1:919362131099:android:a5f64fc9dcedbc60dee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    databaseURL: 'https://fir-series-2d91e-default-rtdb.firebaseio.com',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTUxTAskhz7rctqCBfVUYRbYNOyyB2F7s',
    appId: '1:919362131099:ios:e9c3e455175e0407dee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    databaseURL: 'https://fir-series-2d91e-default-rtdb.firebaseio.com',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestoreDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTUxTAskhz7rctqCBfVUYRbYNOyyB2F7s',
    appId: '1:919362131099:ios:e9c3e455175e0407dee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    databaseURL: 'https://fir-series-2d91e-default-rtdb.firebaseio.com',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    iosBundleId: 'com.example.cloudFirestoreDatabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCD7CByPhwcegRqJASE5qsKeSgCF20ZbM',
    appId: '1:919362131099:web:45abc5dedfffc55adee23e',
    messagingSenderId: '919362131099',
    projectId: 'fir-series-2d91e',
    authDomain: 'fir-series-2d91e.firebaseapp.com',
    databaseURL: 'https://fir-series-2d91e-default-rtdb.firebaseio.com',
    storageBucket: 'fir-series-2d91e.firebasestorage.app',
    measurementId: 'G-YXP1R1WV7D',
  );
}
